# Variables for playbooks

# Whether to set up certain software, configurations
configure_dotfiles: true
configure_extras: true
configure_repos: true

downloads: "{{ dotfiles_home }}/.ansible-downloads"

# Location of this repository
dotfiles_repo: "git@github.com:henningmyhrvold/dotfiles.git"
dotfiles_repo_version: "main"
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "{{ dotfiles_home }}/src/dotfiles"

# Define the home directory for the target user explicitly.
dotfiles_home: "/home/{{ target_user }}"

# User for which set up is being done for
target_user: hm

# Optional location of dotfile overlay
dotfiles_overlay_dir: "{{ playbook_dir }}/../dotfiles-overlay"

# Personal Repositories to be cloned, synchronized
git_repositories:
  # Value of dotfiles_repo variable
  - "{{ dotfiles_repo }}"
