- name: Add RPM Fusion, Microsoft VS Code repositories
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ rpm_repo_keys }}"
  tags: ['dnf', 'workstation-fedora', 'package']
  
- name: Check VS Code repository exists
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/vscode.repo"
  register: vscoderepo
  tags: ['dnf', 'workstation-fedora', 'package']  

- name: Add VS Code Repository to Yum Repos
  ansible.builtin.command: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  when: not vscoderepo.stat.exists
  tags: ['dnf', 'workstation-fedora', 'package']  

- name: Check VS Code repository exists
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/google-kubernetes.repo"
  register: gk8srepo
  tags: ['dnf', 'workstation-fedora', 'package']  

- name: Update listing and install packages
  ansible.builtin.dnf:
    name:
      - "{{ item }}"
    state: latest
  loop: "{{ dnf_installed_packages }}"
  tags: ['dnf', 'workstation-fedora', 'package']  

- name: Remove unneeded packages
  ansible.builtin.dnf:
    name:
    - "{{ item }}"
    state: absent
  loop: "{{ dnf_removed_packages }}"
  tags: ['dnf', 'workstation-fedora', 'package']  

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  tags: ['dnf', 'workstation-fedora', 'package']    

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes
  tags: ['dnf', 'workstation-fedora', 'package']    
