---
- hosts: workstation_arch
  # Run with sudo, root
  become: true

  # Load default variables
  vars_files:
    - host_vars/arch-config.yml

  roles:
    - { role: repos, when: configure_repos, tags: ["repos"] }
    - { role: folders, tags: ["folders"] }
    - { role: pacman, tags: ["pacman"] }
    - { role: rust, tags: ["rust"] }
    - { role: aur, tags: ["aur"] }
    - { role: aur-packages, tags: ["aur-packages"] }
    - { role: audio, tags: ["audio"] }
    - { role: acpi, tags: ["acpi"] }
    - { role: zsh, tags: ["zsh"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: links, tags: ["links"] }
    - { role: copy, tags: ["copy"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: sddm, tags: ["sddm"] }
    - { role: hyprland, tags: ["hyprland"] }
    - { role: permissions, tags: ["permissions"] }
    - { role: luarocks311, tags: ["luarocks311"] }
    - role: thunderbird_headless
      tags: ["thunderbird"]
      vars:
        thunderbird_enable_lingering: true
        thunderbird_refresh_method: "timer"      # "timer" | "runtime_max" | "none"
        thunderbird_refresh_interval: "1min"     # restart cadence
        # thunderbird_use_xvfb: true             # uncomment only if MOZ_HEADLESS still fails
    - { role: apparmor, tags: ["apparmor"] }
    - { role: nftables, tags: ["nftables"] }
    - { role: dns, tags: ["dns"] }
    - { role: wireguard, tags: ["wireguard"] }
    - { role: npm_global, tags: ["npm"] }
    - { role: hwdev_serial, tags: ["hwdev_serial"] }
    - role: docker_engine
      vars:
        docker_users:
          - henning        # adjust to your user
        docker_enable_buildkit: true
        docker_daemon_json_extra:
          # Example extras (optional):
          # "log-driver": "json-file"
          # "log-opts":
          #   "max-size": "10m"
          #   "max-file": "3"
    - { role: docker_mcp, tags: ["docker_mcp"] }
    - { role: mcp_hub_ui, tags: ["mcp_hub_ui"] }
    - { role: claude_desktop_wayland, tags: ["claude_desktop_wayland"] }
    - { role: claude_desktop_mcp_filesystem, tags: ["claude_desktop_mcp_filesystem"] }
    - role: mcp_filesystem
      when: mcp_filesystem_enabled | default(true)
      tags: ["mcp", "mcp_filesystem"]
    - role: mcp_github
      when: mcp_github_enabled | default(true)
      tags: ["mcp", "mcp_github"]
    - role: mcp_ref
      when: mcp_ref_enabled | default(true)
      tags: ["mcp", "mcp_ref"]
    - role: mcp_semgrep
      when: mcp_semgrep_enabled | default(true)
      tags: ["mcp", "mcp_semgrep"]
    # Claude Code CLI (must run after MCP servers)
    - role: claude_code
      tags: ["claude_code"]
