---
- hosts: workstation_arch
  # Run with sudo, root
  become: true

  # Load default variables
  vars_files:
    - host_vars/arch-config.yml

  roles:
    - { role: repos, when: configure_repos, tags: ["repos"] }
    - { role: folders, tags: ["folders"] }
    - { role: pacman, tags: ["pacman"] }
    - { role: rust, tags: ["rust"] }
    - { role: aur, tags: ["aur"] }
    - { role: aur-packages, tags: ["aur-packages"] }
    - { role: audio, tags: ["audio"] }
    - { role: acpi, tags: ["acpi"] }
    - { role: zsh, tags: ["zsh"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: links, tags: ["links"] }
    - { role: copy, tags: ["copy"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: sddm, tags: ["sddm"] }
    - { role: hyprland, tags: ["hyprland"] }
    - { role: permissions, tags: ["permissions"] }
    - { role: luarocks311, tags: ["luarocks311"] }
    - role: thunderbird_headless
      tags: ["thunderbird"]
      vars:
        thunderbird_enable_lingering: true
        thunderbird_refresh_method: "timer"      # "timer" | "runtime_max" | "none"
        thunderbird_refresh_interval: "1min"     # restart cadence
        # thunderbird_use_xvfb: true             # uncomment only if MOZ_HEADLESS still fails
    - { role: apparmor, tags: ["apparmor"] }
    - { role: nftables, tags: ["nftables"] }
    - { role: wireguard, tags: ["wireguard"] }
