---
- hosts: workstation_arch
  # Run with sudo, root
  become: true

  # Load default variables
  vars_files:
    - host_vars/arch-config.yml

  roles:
    - { role: repos, when: configure_repos, tags: ["repos"] }
    - { role: pacman, tags: ["pacman"] }
    - { role: aur, tags: ["aur"] }
    - { role: folders, tags: ["folders"] }
    - { role: audio, tags: ["audio"] }
    - { role: acpi, tags: ["acpi"] }
    - { role: zsh, tags: ["zsh"] }
    - { role: rust, tags: ["rust"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: links, tags: ["links"] }
    - { role: copy, tags: ["copy"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: sddm, tags: ["sddm"] }
    - { role: hyprland, tags: ["hyprland"] }
    - { role: permissions, tags: ["permissions"] }
    - { role: luarocks311, tags: ["luarocks311"] }
    - { role: zen-extensions, tags: ["zen-extensions"] }
