---
- hosts: workstation_arch
  # Run with sudo, root
  become: true

  # Load default variables
  vars_files:
    - host_vars/arch-config.yml

  roles:
    - { role: repos, when: configure_repos, tags: ["repos"] }
    - pacman
    - aur
    - { role: zsh, tags: ["zsh"] }
    - { role: hyprland, tags: ["hyprland"] }
    - { role: rust, tags: ["rust"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: links, tags: ["links"] }
    - { role: sddm, tags: ["sddm"] }
    - { role: dotfiles, when: configure_dotfiles, tags: ["dotfiles"] }
