---
- hosts: workstation_debian
  # Run as root
  become: true

  # Load default variables
  vars_files:
    - host-vars/debian-config.yml

  # Load override
  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]
    - name: Include overlay configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ dotfiles_overlay_dir }}/config-debian.yml"
      tags: ["always"]

  roles:
    - debian
    - { role: dotfiles, when: configure_dotfiles, tags: ["dotfiles"] }
    - { role: repos, when: configure_repos, tags: ["repos"] }
    - { role: rust, tags: ["rust"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: fonts, tags: ["fonts"] }
