---
- hosts: workstation_debian
  # Run as root
  become: true

  # Load default variables
  vars_files:
    - host_vars/debian-config.yml

  roles:
    - { role: repos, when: configure_repos, tags: ["repos"] }
    - debian
    - { role: tmux, tags: ["tmux"] }
