---
- hosts: workstation_fedora
  # Run with sudo, root
  become: true

  # Load default variables
  vars_files:
    - host_vars/fedora-config.yml
    
  roles:
    - { role: repos, when: configure_repos, tags: ["repos"] }
    - fedora
    - { role: tmux, tags: ["tmux"] }
