---
- hosts: workstation_fedora
  # Run with sudo, root
  become: true

  # Load default variables
  vars_files:
    - host_vars/fedora-config.yml
    
  roles:
    - { role: repos, when: configure_repos, tags: ["repos"] }
    - fedora
    - { role: rust, tags: ["rust"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: dotfiles, when: configure_dotfiles, tags: ["dotfiles"] }
