# Modify GNOME Settings in loop
- name: GNOME - Modify settings
  community.general.dconf:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
      state: present
  loop:
      # Idle screen lock timeout
      - { key: "/org/gnome/desktop/session/idle-delay", value: "900" }
      # Remove lock screen from screensaver
      - { key: "/org/gnome/desktop/screensaver/lock-enabled", value: "false" }
      # Set gtk theme, ' ' required for strings
      - {
            key: "/org/gnome/desktop/interface/gtk-theme",
            value: "'Adwaita-dark'",
        }
      # Disable problem reporting
      - {
            key: "/org/gnome/desktop/privacy/report-technical-problems",
            value: "false",
        }
      # Disable stat reporting
      - {
            key: "/org/gnome/desktop/privacy/send-software-usage-stats",
            value: "false",
        }
      # Show weekday in clock
      - {
            key: "/org/gnome/desktop/interface/clock-show-weekday",
            value: "true",
        }
      
  tags: ["workstation-fedora", "workstation-debian", "gnome", "desktop"]

