---
- name: Set up apt packages
  import_tasks: tasks/debian/apt.yml
  tags: ["workstation-debian", "apt", "package", "laptop-debian"]
  when: ansible_distribution == "Debian"

- name: Set up pacman packages
  import_tasks: tasks/arch/pacman.yml
  tags: ["workstation-arch", "pacman", "package"]
  when: ansible_distribution == "Archlinux"

- name: Set up dnf packages
  import_tasks: tasks/fedora/dnf.yml
  tags: ["workstation-fedora", "dnf", "package"]
  when: ansible_distribution == "Fedora"

- name: Set up Python packages
  import_tasks: tasks/python.yml
  tags:
    [
      "workstation-debian",
      "python",
      "laptop-debian",
      "workstation-fedora",
      "workstation-arch",
    ]

- name: Set up Rust packages
  import_tasks: tasks/rust.yml
  tags:
    [
      "workstation-debian",
      "rust",
      "package",
      "laptop-debian",
      "workstation-fedora",
    ]

- name: Configure Gnome settings
  import_tasks: tasks/gnome.yml
  tags: ["workstation-debian", "gnome", "desktop", "workstation-fedora"]
  when: configure_gnome

- name: Set up Gnome dnf packages

  import_tasks: tasks/fedora/dnf-gnome.yml
  tags: ["workstation-fedora", "dnf-gnome", "package", "workstation-fedora"]
  when: configure_gnome and ansible_distribution == "Fedora"

- name: Set up other Fedora settings
  import_tasks: tasks/fedora/other.yml
  tags: ["workstation-fedora", "other"]
  when: ansible_distribution == "Fedora"

- name: Synchronize git repositories
  import_tasks: tasks/repos.yml
  tags: ["workstation-debian", "laptop-debian", "repos", "workstation-fedora"]
  when: configure_repos

- name: Set up Neovim
  import_tasks: tasks/nvim.yml
  tags:
    [
      "workstation-debian",
      "laptop-debian",
      "nvim",
      "workstation-fedora",
      "workstation-arch",
    ]

- name: Set up and synchronize dotfiles
  import_tasks: tasks/dotfiles.yml
  when: configure_dotfiles
  tags:
    [
      "workstation-debian",
      "workstation-fedora",
      "laptop-debian",
      "dotfiles",
      "workstation-arch",
    ]

- name: Set up fonts
  import_tasks: tasks/fonts.yml
  when: configure_dotfiles
  tags: ["workstation-debian", "workstation-fedora", "laptop-debian", "fonts"]

- name: Set up tmux
  import_tasks: tasks/tmux.yml
  tags: ["workstation-debian", "laptop-debian", "tmux", "workstation-fedora"]

