# Install rust
- name: rust - add rustup, accept defaults
  ansible.builtin.shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  tags: ["workstation-debian", "rust", "package", "workstation-fedora"]
  become: true
  become_user: "{{ target_user }}"

- name: rust - add rust-analyzer, clippy, rustfmt
  ansible.builtin.shell: "$HOME/.cargo/bin/rustup component add rustfmt clippy rust-analyzer"
  tags: ["workstation-debian", "rust", "package", "workstation-fedora"]
  become: true
  become_user: "{{ target_user }}"
