---
# All dotfile directories that must exist
- name: Create parent directories for links
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    owner: "{{ target_user }}"
    mode: '0755'
  loop: "{{ dotfiles_links + regular_links }}"
  recurse: yes
  tags: ["dotfiles", "dotfiles-setup"]

- name: dotfiles - Link dotfiles into home folder
  ansible.builtin.file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item.src }}"
    dest: "{{ dotfiles_home }}/{{ item.dest }}"
    state: link
    force: true 
    owner: "{{ target_user }}"
    mode: "0644"
  loop: "{{ dotfiles_links }}"
  become: true
  become_user: "{{ target_user }}"
  tags: ["dotfiles", "dotfiles-symlink"]

- name: dotfiles - Ensure specified scripts are executable
  ansible.builtin.file:
    path: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    mode: "0755"
  with_items: "{{ dotfiles_files_binaries }}"
  when: dotfiles_files_binaries is defined
  become: true
  become_user: "{{ target_user }}"
  tags: ["dotfiles", "dotfiles-symlink-binaries"]
