---
- name: links - Link files with full paths
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true 
    owner: "{{ target_user }}"
    mode: "0644"
  loop: "{{ regular_links }}"
  become: true
  become_user: "{{ target_user }}"
  tags: ["links", "symlink"]
