- name: dnf - Update listing and install packages
  ansible.builtin.dnf:
    name:
      - "{{ item }}"
    state: latest
  loop: "{{ dnf_installed_packages_gnome }}"
  tags: ['dnf-gnome', 'workstation-fedora', 'package']
