# Update homebrew and upgrade all packages
- name: Update and upgrade all installed packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  tags: ["homebrew", "workstation-macos", "package"]
  become_user: "{{ target_user }}"
