# tasks/arch/aur.yml
---
- name: AUR - Build paru from cloned source
  ansible.builtin.shell:
    cmd: "makepkg -s --noconfirm"
    chdir: "/home/{{ target_user }}/src/external/paru-git"
  become: false
  when: not ansible_check_mode
  register: build_result

- name: AUR - Install paru
  ansible.builtin.shell:
    cmd: "pacman -U --noconfirm /home/{{ target_user }}/src/external/paru-git/*.pkg.tar.zst"
    become: true
    become_user: root
  when: build_result.changed and not ansible_check_mode
  args:
    creates: /usr/bin/paru

- name: AUR - Install packages from aur_installed_packages list
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: paru
    state: present
  with_items: "{{ aur_installed_packages }}"
  become: true
  become_user: "{{ target_user }}"
  when: aur_installed_packages is defined
