--- 
- name: pacman - Update package database
  community.general.pacman:
    update_cache: true
  tags: ['pacman', 'workstation-arch', 'package']

- name: pacman - Install base-devel and git for AUR support
  community.general.pacman:
    name:
      - base-devel
      - git
    state: present
  tags: ['pacman', 'workstation-arch', 'package']
 
- name: pacman - Update listing and install packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ pacman_installed_packages }}"
  tags: ['pacman', 'workstation-arch', 'package']

- name: pacman - enable color
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#Color$'
    line: 'Color'

- name: pacman - enable ParallelDownloads = 5
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#ParallelDownloads = 5'
    line: 'ParallelDownloads = 5'

- name: pacman - enable multilib repository
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#\\[multilib\\]'
    line: '[multilib]'

- name: pacman - enable multilib mirrorlist include
  lineinfile:
    path: /etc/pacman.conf
    regexp: '#Include = /etc/pacman.d/mirrorlist'
    line: 'Include = /etc/pacman.d/mirrorlist'
    insertafter: '\\[multilib\\]'
