- name: tmux - Set up tmux package manager
  ansible.builtin.git:
    repo: "git@github.com:tmux-plugins/tpm.git"
    dest: "/home/{{ target_user }}/.tmux/plugins/tpm"
    force: no
  become: true
  become_user: "{{ target_user }}"
  tags: ['workstation-debian', 'tmux', 'workstation-fedora']
