# Task for user-owned directories
- name: Create user-owned directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
  loop: "{{ create_folders | selectattr('path', 'match', '^/home/') | list }}"
  become: true
  become_user: "{{ target_user }}"
  tags: ["folders"]

# Task for system directories
- name: Create system directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    mode: "0755"
  loop: "{{ create_folders | selectattr('path', 'match', '^/usr/|^/etc/') | list }}"
  become: true
  tags: ["folders"]
