# Variables for playbooks for Arch Linux

# --- Pacman Packages ---
pacman_installed_packages:
  # Wayland and Hyprland
  - wayland
  - hyprland
  - libinput
  - qt5-wayland 
  - qt6-wayland
  - xdg-desktop-portal-hyprland
  # --- Graphics Drivers ---
  - mesa
  # --- Audio ---
  - pipewire
  - wireplumber
  - pipewire-pulse
  - pipewire-alsa
  # --- Display & Theming ---
  - waybar
  - wofi
  - swaybg
  - swaylock
  - dunst
  - ranger
  - polkit-kde-agent
  - noto-fonts
  - noto-fonts-emoji
  - ttf-cascadia-code-nerd
  # --- CLI Tools & Shell ---
  - neovim
  - zsh
  - tmux
  - wget
  - fzf
  - bat
  - ripgrep

# --- AUR Packages ---
aur_installed_packages:
  - eww-wayland
  - cool-retro-term

# --- Dotfiles Configuration ---
configure_dotfiles: true

# These directories will be created if they don't exist.
dotfiles_directories:
  - "{{ dotfiles_home }}/.config/nvim"
  - "{{ dotfiles_home }}/.config/tmux"
  - "{{ dotfiles_home }}/.config/wezterm"
  - "{{ dotfiles_home }}/.config/hypr"
  - "{{ dotfiles_home }}/.config/waybar"
  - "{{ dotfiles_home }}/.config/wofi"
  - "{{ dotfiles_home }}/.config/dunst"
  - "{{ dotfiles_home }}/.config/eww"
  - "{{ dotfiles_home }}/.config/ranger"
  - "{{ dotfiles_home }}/.config/cool-retro-term"

# Defines symlinks from the dotfiles repo to the home directory.
dotfiles_links:
  - { src: "zsh/.zshrc", dest: ".zshrc" }
  - { src: "zsh/.p10k.zsh", dest: ".p10k.zsh" }
  - { src: "nvim/init.vim", dest: ".config/nvim/init.vim" }
  - { src: "nvim/keymappings.lua", dest: ".config/nvim/keymappings.lua" }
  - { src: "tmux/tmux.conf", dest: ".config/tmux/tmux.conf" }
  - { src: "wezterm/wezterm.lua", dest: ".config/wezterm/wezterm.lua" }
  - { src: "hypr/hyprland.conf", dest: ".config/hypr/hyprland.conf" }
  - { src: "hypr/hyprpaper.conf", dest: ".config/hypr/hyprpaper.conf" }
  - { src: "waybar/desktop-bar/config", dest: ".config/waybar/config" }
  - { src: "waybar/desktop-bar/style.css", dest: ".config/waybar/style.css" }
  - { src: "wofi/config", dest: ".config/wofi/config" }
  - { src: "wofi/style.css", dest: ".config/wofi/style.css" }
  - { src: "dunst/dunstrc", dest: ".config/dunst/dunstrc" }
  - { src: "eww/eww.yuck", dest: ".config/eww/eww.yuck" }
  - { src: "eww/eww.scss", dest: ".config/eww/eww.scss" }
  - { src: "ranger/rc.conf", dest: ".config/ranger/rc.conf" }
  - { src: "ranger/rifle.conf", dest: ".config/ranger/rifle.conf" }
  - { src: "ranger/commands.py", dest: ".config/ranger/commands.py" }
  - { src: "ranger/scope.sh", dest: ".config/ranger/scope.sh" }
  - { src: "cool-retro-term/cool-retro-term-my-futuristic.json", dest: ".config/cool-retro-term/cool-retro-term-my-futuristic.json"}

# --- Git Repositories ---
git_repositories_external:
  - https://aur.archlinux.org/paru-git.git

# --- Scripts to make executable ---
dotfiles_files_binaries:
  - "hypr/scripts/focused-window"
  - "hypr/scripts/get-last-focused-window.sh"
  - "hypr/toggle-gaps.sh"
  - "waybar/scripts/dunst.sh"
  - "waybar/scripts/mediaplayer.py"
  - "waybar/scripts/power-menu/powermenu.sh"
  - "waybar/scripts/rofi-wifi-menu.sh"
  - "waybar/scripts/spotify.sh"
  - "waybar/scripts/weather.py"
  - "wofi/powermenu.sh"
  - "wofi/wifimenu.sh"
  - "eww/scripts/activewin"
  - "eww/scripts/activews"
  - "eww/scripts/focuswindow"
  - "eww/scripts/get-icon.py"
  - "eww/scripts/overview1"
  - "eww/scripts/overview2"
  - "eww/scripts/selectwindow"
  - "eww/scripts/winlist"
  - "eww/scripts/winnumbers"
  - "eww/scripts/workspaces"
