# Variables for playbooks for Arch Linux

# --- Pacman Packages ---
pacman_installed_packages:
  # --- Wayland ---
  - wayland
  - wlr-randr
  - xorg-xwayland
  - xdg-desktop-portal-hyprland
  - xdg-utils
  - qt5-wayland 
  - qt6-wayland
  # --- Hyprland ---
  - hyprland
  - hyprpaper
  - hypridle
  - hyprlock
  - hyprsunset
  - hyprutils
  # --- Auth ---
  - sddm
  # --- Graphics Drivers ---
  - mesa
  # --- Audio ---
  - pipewire
  - wireplumber
  # --- Networking ---
  - wireless_tools
  - wpa_supplicant
  # --- Display & Theming ---
  - libinput
  - waybar
  - wofi
  - swaybg
  - swaylock
  - dunst
  - polkit-kde-agent
  - grim
  - slurp
  # --- Fonts ---
  - noto-fonts
  - noto-fonts-emoji
  - ttf-cascadia-code-nerd
  # --- GUI File manager ---
  #- nautilus
  - dolphin
  # --- CLI Tools & Shell ---
  - neovim
  - zsh
  - tmux
  - wget
  - fzf
  - bat
  - ripgrep
  - htop
  - kitty
  - smartmontools
  - cliphist
  - unzip
  - rsync

# --- AUR Packages ---
aur_installed_packages:
  - eww-git
  - oh-my-zsh-git
  - zsh-theme-powerlevel10k-git
  - ttf-meslo-nerd-font-powerlevel10k
  - cool-retro-term

# --- Dotfiles Configuration ---
configure_dotfiles: true

# These directories will be created if they don't exist.
dotfiles_directories:
  - "{{ dotfiles_home }}/.config/nvim"
  - "{{ dotfiles_home }}/.config/tmux"
  - "{{ dotfiles_home }}/.config/wezterm"
  - "{{ dotfiles_home }}/.config/hypr"
  - "{{ dotfiles_home }}/.config/waybar"
  - "{{ dotfiles_home }}/.config/wofi"
  - "{{ dotfiles_home }}/.config/dunst"
  - "{{ dotfiles_home }}/.config/eww"
  - "{{ dotfiles_home }}/.config/cool-retro-term"
  - "{{ dotfiles_home }}/.zsh"

# Defines symlinks from the dotfiles repo to the home directory.
dotfiles_links:
  - { src: "zsh/.zshrc", dest: ".zshrc" }
  - { src: "zsh/.p10k.zsh", dest: ".p10k.zsh" }
  - { src: "zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh", dest: ".zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh" }
  - { src: "nvim/init.vim", dest: ".config/nvim/init.vim" }
  - { src: "nvim/keymappings.lua", dest: ".config/nvim/keymappings.lua" }
  - { src: "tmux/tmux.conf", dest: ".config/tmux/tmux.conf" }
  - { src: "wezterm/wezterm.lua", dest: ".config/wezterm/wezterm.lua" }
  - { src: "hypr/hyprland.conf", dest: ".config/hypr/hyprland.conf" }
  - { src: "hypr/hyprpaper.conf", dest: ".config/hypr/hyprpaper.conf" }
  - { src: "hypr/mocha.conf", dest: ".config/hypr/mocha.conf" }
  - { src: "waybar/desktop-bar/config", dest: ".config/waybar/config" }
  - { src: "waybar/desktop-bar/style.css", dest: ".config/waybar/style.css" }
  - { src: "wofi/config", dest: ".config/wofi/config" }
  - { src: "wofi/style.css", dest: ".config/wofi/style.css" }
  - { src: "dunst/dunstrc", dest: ".config/dunst/dunstrc" }
  - { src: "eww/eww.yuck", dest: ".config/eww/eww.yuck" }
  - { src: "eww/eww.scss", dest: ".config/eww/eww.scss" }
  - { src: "cool-retro-term/cool-retro-term-my-futuristic.json", dest: ".config/cool-retro-term/cool-retro-term-my-futuristic.json"}

regular_links:
  - { src: "/usr/share/zsh-theme-powerlevel10k", dest: "/usr/share/oh-my-zsh/custom/themes/powerlevel10k" }
  - { src: "{{ dotfiles_home }}/src/dotfiles/sddm/sddm.conf", dest: "/etc/sddm.conf" }

copy:
  - { src: "{{ dotfiles_home }}/src/dotfiles/sddm/catppuccin-mocha/", dest: "/usr/share/sddm/themes/catppuccin-mocha/" }
  
# --- Git Repositories ---
git_repositories_external:
  - https://aur.archlinux.org/paru-git.git

# --- Scripts to make executable ---
dotfiles_files_binaries:
  - "hypr/scripts/focused-window"
  - "hypr/scripts/get-last-focused-window.sh"
  - "hypr/toggle-gaps.sh"
  - "waybar/scripts/dunst.sh"
  - "waybar/scripts/mediaplayer.py"
  - "waybar/scripts/power-menu/powermenu.sh"
  - "waybar/scripts/rofi-wifi-menu.sh"
  - "waybar/scripts/spotify.sh"
  - "waybar/scripts/weather.py"
  - "wofi/powermenu.sh"
  - "wofi/wifimenu.sh"
  - "eww/scripts/activewin"
  - "eww/scripts/activews"
  - "eww/scripts/focuswindow"
  - "eww/scripts/get-icon.py"
  - "eww/scripts/overview1"
  - "eww/scripts/overview2"
  - "eww/scripts/selectwindow"
  - "eww/scripts/winlist"
  - "eww/scripts/winnumbers"
  - "eww/scripts/workspaces"
  - /usr/share/zsh-theme-powerlevel10k
