# Variables for playbooks
# --- Dotfiles Configuration ---
configure_dotfiles: true

# These directories will be created if they don't exist.
dotfiles_directories:
  - "{{ dotfiles_home }}/.config/tmux"

# Defines symlinks from the dotfiles repo to the home directory.
dotfiles_links:
  - { src: "tmux/tmux.conf", dest: ".config/tmux/tmux.conf" }

dnf_installed_packages:
  - git
  - tmux

