- name: Debug before permissions
  debug:
    msg: "{{ before_permissions.stdout | default('Directory not found') }}"

- name: Ensure powerlevel10k theme directory has execute permissions
  file:
    path: /usr/share/zsh-theme-powerlevel10k
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: yes
  tags: ["permissions"]

- name: Check current permissions after
  command: ls -ld /usr/share/zsh-theme-powerlevel10k
  register: after_permissions
  become: yes

- name: Debug after permissions
  debug:
    msg: "{{ after_permissions.stdout }}"

- name: Grant reboot permission without sudo password
  lineinfile:
    path: /etc/sudoers.d/reboot-permissions
    create: yes
    owner: root
    group: root
    mode: "0440"
    line: '{{ ansible_user_id }} ALL=(ALL) NOPASSWD: /sbin/reboot'
    validate: 'visudo -cf %s'
  become: yes
  tags: ["permissions"]
